apiVersion: apps/v1
kind: Deployment
metadata:
  name:  logging-logstash
  labels:
    name:  logging-logstash
spec:
  replicas: 2
  selector:
    matchLabels:
      task: logging
      k8s-app: logstash
  template:
    metadata:
      labels:
        task: logging
        k8s-app: logstash
        name: logging-logstash
    spec:
      containers:
      - name: llogging-logstash
        image: docker.elastic.co/logstash/logstash:8.1.2
        ports:
          - containerPort: 5044